# kubernetes/codimd-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codimd
  namespace: codimd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codimd
  template:
    metadata:
      labels:
        app: codimd
    spec:
      initContainers:
        - name: setup-db-url
          image: busybox:1.35
          command:
            - sh
            - -c
            - |
              echo "postgres://codimd:${DB_PASSWORD}@postgresql:5432/codimd" > /shared/db-url
              echo "Database URL prepared"
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: codimd-db-secrets
                  key: password
          volumeMounts:
            - name: shared-data
              mountPath: /shared
      containers:
        - name: codimd
          image: hackmdio/hackmd:2.5.4
          command:
            - sh
            - -c
            - |
              export CMD_DB_URL=$(cat /shared/db-url)
              echo "Starting CodiMD with database connection..."
              exec node app.js
          env:
            # セッション設定
            - name: CMD_SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: codimd-app-secrets
                  key: session-secret

            # 基本設定
            - name: CMD_DOMAIN
              value: "md.andex.tokyo"
            - name: CMD_URL_ADDPORT
              value: "false"
            - name: CMD_PROTOCOL_USESSL
              value: "true"

            # アクセス制御設定
            - name: CMD_ALLOW_ANONYMOUS
              value: "false"
            - name: CMD_ALLOW_ANONYMOUS_EDITS
              value: "false"
            - name: CMD_ALLOW_FREEURL
              value: "true"
            - name: CMD_REQUIRE_FREEURL_AUTHENTICATION
              value: "true"
            - name: CMD_DEFAULT_PERMISSION
              value: "editable"

            # 認証設定
            - name: CMD_EMAIL
              value: "true"
            - name: CMD_ALLOW_EMAIL_REGISTER
              value: "true"

            # 画像アップロード設定（Cloudflare R2）
            - name: CMD_IMAGE_UPLOAD_TYPE
              value: "s3"
            - name: CMD_S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: codimd-s3-secrets
                  key: access-key
            - name: CMD_S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: codimd-s3-secrets
                  key: secret-key
            - name: CMD_S3_REGION
              value: "auto"
            - name: CMD_S3_BUCKET
              value: "andex-codimd"
            - name: CMD_S3_ENDPOINT
              value: "https://md-file.andex.tokyo"
            - name: CMD_S3_FORCE_PATH_STYLE
              value: "false"

            # その他設定
            - name: CMD_ALLOW_PDF_EXPORT
              value: "true"
            - name: CMD_ALLOW_GRAVATAR
              value: "true"

          ports:
            - containerPort: 3000
          volumeMounts:
            - name: shared-data
              mountPath: /shared

          readinessProbe:
            httpGet:
              path: /status
              port: 3000
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /status
              port: 3000
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
      volumes:
        - name: shared-data
          emptyDir: {}
