---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: codimd-s3-secrets
  namespace: codimd
spec:
  encryptedData:
    access-key: AgAphSMjUb80gQYRcHKx8KWFNG6TSD2ocqD4h7I7dVGysmPwgd6QpTaiA+0PBtnBS4kmaRxpRqzdAqSzuBdYBGSle59j6jFmt2zAuwcJ3cAmyLAVNu2ClSz7UzQZQoSOGlRmenWY6J8T7gOpiDjhFkToft1YTnFGdjGnYnj/aFTpMgodcEAAlN3opwbKjPkmSD7Pi5NVu5A4RdHfz87sxvNYBGkHBaOBm8OX5B7dovs32ucLaZpdsjsoDDdOc9eAynm8U+ukCWYqHkfvHwbc179WI/V/sz5oaDMamfUVFtFQIFzXA0WWh5/IWcCEN3L1sNfQ/Wg95jpvEfd2v2Sjjsw4/RFzSJ6a/lzNmoAqnOqsgRVByhzrkA10ePazV7fZ0yF+PeQDmWr/ntThcZ6CPYnT5Iu1ZdGA55g9lo9n7nqlGstancT0M9ujilrkLWb+FhL1CEJL7BIjieoAqO414qyRD4ivPa0cAIVSCXRC4UoRj5ohe5rK6Vbf8xC9W7vkgt8Nc19npDkM+WCEOLYvKy6HR1pBkGXvJ3YT6Mjaqbd4yoiwupgwDw0g+50enhZHHTKM2Hn2RYiRiEpb5gMKfZFWS2iBUJ+i86FDveQhqkc/2mh656ap2EOVyQyU339JC1ON7d+He056vvhLZbbw0UoK8E5uvF028EcR/80A5dnJeBxDY9r7IoZ6Opxfw2BgtHoc2qjuv/7vZDJg0bBDdq/q7HF7KEmKTgXeSkdiJmy/Fg==
    secret-key: AgAOumzE1WYTz+F74RSUrbgwr5bnLYa6mvg2+zQCSwynKNlYC06oX52UhDYPdTSxlOghnl7nxXLNfqZoRhDhmtnzdNbMjfMuHwYikXt/E9DaQ/+jKV1CpcYryp5ExQzik35lj9OUW/TOWWDiaOLw6cpojPUNtvDtTYZc34BLW6Wj6xwUKl1ZPsyr7cWw82xzd6ZpM4wWnJbHubOos/l8/HG0pszA4V0niDSjKxR9cWbN0ioA9O+HD3k7wP1jklfa/VTEA2FwGHFZI+7aiuOwBWwX5EcfHMm0kFmU4L6MpNdkMuIIROC/hYDUgqPnOT6FizO1P9SalBB/Jc7MtIRyjl8MAbUAt9Bk352I3GVvKkTyxSmBj9kcNxmOIWRDODGlg5yOiUrtiRt79bqHbFtKCsPGjStZt9ezVOiA+xybgf3vIF/9eMC45X5lEhJR/ZJE1h9gXIHbiFHr9kjG1ncOadPFcesVUUrnZtRdKvj6GMToj7Q7Fdvx/Nhw9+KNg0Pp+NnEvYVUHOv7rl+hangsrkQ3tdvLwy44YHzI0uXaqs189tclSEUVj20bTPi7I73avVNvwAeEG+2jDKEls58aq9H4MnUc0z9zYVhIuX3uFaEJ0bkiIvapzU7hfAT43fbwD7L+JKrDQin+Mnz5qvxHps77rwInaby3Xt0epD8VwVk0CmOV1UNB0sKOuiaMBxiI8tWNlIC6yzkZiC5426IHfNT1yIWPF24JzpygObzNw9VPXHiqdkbMQ89vRvbuIRtTiiWABxq1j0evXkT8FEpDPHA/
  template:
    metadata:
      creationTimestamp: null
      name: codimd-s3-secrets
      namespace: codimd
